services:
  gateway:
    container_name: starter-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3344:3000
    environment:
      - APP=gateway
    networks:
      - internal
  provider:
    container_name: starter-provider
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - APP=provider
    networks:
      - internal
  schedule:
    container_name: starter-schedule
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - APP=schedule
    networks:
      - internal
networks:
  internal:
    external: true
