name: starter-nestjs

services:
  app:
    env_file:
      - ../.env
    container_name: starter-nestjs
    build:
      context: .
      dockerfile: Dockerfile.deploy
    ports:
      - 3000:3000
    networks:
      - internal
networks:
  internal:
    external: true
